spring.application.name=usuario-service
spring.profiles.active = dev # Es el perfil por defecto, toma el archivo application-dev.properties
# spring.profiles.active = prod
# spring.profiles.active = cert