# Base de datos
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=usuariodb;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Admin1234!

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
